# Generated by Django 4.1.2 on 2022-11-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_orderitem_qunatity_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
