# Generated by Django 4.1.2 on 2022-11-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_order_city_remove_order_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
